#!/bin/bash

URL=$1

#URL="https://www.youtube.com/watch?v=FNzSF-0TM2w"

nombreOriginal=$(yt-dlp --get-filename -o "%(title)s.%(ext)s" "$URL")
echo "nombreOriginal=$nombreOriginal"

nombreSrc=$(echo "$nombreOriginal" | sed 's/[^a-zA-Z0-9. ]//g; s/á/a/g; s/é/e/g; s/í/i/g; s/ó/o/g; s/ú/u/g; s/Á/A/g; s/É/E/g; s/Í/i/g; s/Ó/O/g; s/Ú/U/g; s/º//g; s/  / /g ' | sed 's/ /_/g' | sed 's/.webm//g')
echo "nombreSrc=$nombreSrc"

echo "Descargando el video"
yt-dlp -f 'best[height<=1080]+bestaudio/best' -o "./contenido/$nombreSrc.%(ext)s" "$URL"

echo "Descargando miniatura"
yt-dlp --get-thumbnail -o "%(thumbnail)s" "$URL" | xargs -I {} curl -S -o ./contenido/"$nombreSrc".jpg {}